name: Deploy

on:
  push: [ main ]
  workflow_dispatch:

jobs:
  django-deploy:
    needs: [lint-black]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
        pipenv install

    - name: Create .env
      run: |
        echo "DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY" > .env
        echo "UP_EMAIL=$UP_EMAIL" >> .env
      env:
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        UP_EMAIL: ${{ secrets.UP_EMAIL }}

    - name: Setup SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        known_hosts: unnecessary

    - name: Accept host fingerprint
      run: |
        ssh -o StrictHostKeyChecking=accept-new root@django-up.com "ls"

    - name: Run up
      run: ./deploy.sh
      env:
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        UP_EMAIL: ${{ secrets.UP_EMAIL }}

    - name: Remove .env
      run: rm .env

